import 'dart:math';
import 'package:flutter/material.dart';
import '../services/sound_service.dart';
import '../widgets/confetti_overlay.dart';
import '../widgets/game_header.dart';

class AirHockeyPage extends StatefulWidget { const AirHockeyPage({super.key}); @override State<AirHockeyPage> createState()=>_AirHockeyPageState(); }
class _AirHockeyPageState extends State<AirHockeyPage> with SingleTickerProviderStateMixin {
  final confettiKey=GlobalKey<ConfettiOverlayState>(); late final AnimationController clock;
  Offset puck=const Offset(.5,.5),velocity=const Offset(.004,.006),bottom=const Offset(.5,.84),top=const Offset(.5,.16),bottomVelocity=Offset.zero,topVelocity=Offset.zero;int bottomScore=0,topScore=0;bool bot=true,playing=true;
  @override void initState(){super.initState();clock=AnimationController(vsync:this,duration:const Duration(seconds:1))..addListener(_tick)..repeat();}
  void _tick(){if(!mounted||!playing)return;var p=puck+velocity,v=velocity*.999;if(bot&&p.dy<.58){final old=top;top=Offset((top.dx+(p.dx-top.dx)*.022).clamp(.14,.86),.16);topVelocity=top-old;}else if(bot){topVelocity=Offset.zero;}if(p.dx<.045||p.dx>.955){v=Offset(-v.dx,v.dy);p=Offset(p.dx.clamp(.045,.955),p.dy);}v=_collide(bottom,p,bottomVelocity,true,v);v=_collide(top,p,topVelocity,false,v);bottomVelocity*=.82;topVelocity*=.82;if(p.dy<0){bottomScore++;_goal(true);return;}if(p.dy>1){topScore++;_goal(false);return;}setState((){puck=p;velocity=v;});}
  Offset _collide(Offset paddle,Offset p,Offset paddleSpeed,bool lower,Offset current){final d=p-paddle;if(d.distance>=.105||d.distance==0||(lower?current.dy<=0:current.dy>=0))return current;final n=d/d.distance;var result=n*.0065+paddleSpeed*1.15;final speed=result.distance.clamp(.005, .019).toDouble();result=result/result.distance*speed;SoundService.instance.play('tap.wav');return result;}
  void _goal(bool human){SoundService.instance.play('chime.wav');if(bottomScore>=5||topScore>=5){playing=false;confettiKey.currentState?.burst(count:34);SoundService.instance.play('win.wav');}setState((){puck=const Offset(.5,.5);velocity=Offset((Random().nextDouble()-.5)*.006,human?0.006:-0.006);});}
  void _reset(){setState((){bottomScore=0;topScore=0;playing=true;puck=const Offset(.5,.5);velocity=const Offset(.004,.006);bottom=const Offset(.5,.84);top=const Offset(.5,.16);bottomVelocity=Offset.zero;topVelocity=Offset.zero;});}
  Offset _limit(Offset value,double max){return value.distance>max?value/value.distance*max:value;}
  void _movePointer(PointerEvent e,BoxConstraints c){final local=e.localPosition;final x=(local.dx/c.maxWidth).clamp(.1,.9),y=(local.dy/c.maxHeight).clamp(.08,.92);if(y>.5){final next=Offset(x,y.clamp(.56,.92));bottomVelocity=_limit(next-bottom,.028);bottom=next;}else if(!bot){final next=Offset(x,y.clamp(.08,.44));topVelocity=_limit(next-top,.028);top=next;}}
  @override void dispose(){clock.dispose();super.dispose();}
  @override Widget build(BuildContext context)=>ConfettiOverlay(key:confettiKey,child:Padding(padding:const EdgeInsets.fromLTRB(14,8,14,12),child:Column(children:[
    GameHeader(title:'الهوكي الهوائي',subtitle:playing?'الأول الذي يسجل 5 أهداف يفوز':(bottomScore>topScore?'فاز اللاعب 1 🎉':'فاز ${bot?'الروبوت':'اللاعب 2'} 🎉'),color:const Color(0xFF0891B2),onReset:_reset),
    const SizedBox(height:7),Row(children:[Expanded(child:ChoiceChip(label:const Text('ضد الروبوت'),selected:bot,onSelected:(_){bot=true;_reset();})),const SizedBox(width:8),Expanded(child:ChoiceChip(label:const Text('مع صديق'),selected:!bot,onSelected:(_){bot=false;_reset();}))]),const SizedBox(height:7),
    Row(mainAxisAlignment:MainAxisAlignment.center,children:[_Score(name:'اللاعب 1',score:bottomScore,color:const Color(0xFF22D3EE)),const SizedBox(width:18),_Score(name:bot?'الروبوت':'اللاعب 2',score:topScore,color:const Color(0xFFF472B6))]),const SizedBox(height:8),
    Expanded(child:LayoutBuilder(builder:(context,c)=>Listener(onPointerDown:(e)=>_movePointer(e,c),onPointerMove:(e)=>_movePointer(e,c),child:CustomPaint(size:Size(c.maxWidth,c.maxHeight),painter:_HockeyPainter(puck,bottom,top)))))
  ])));
}
class _Score extends StatelessWidget{const _Score({required this.name,required this.score,required this.color});final String name;final int score;final Color color;@override Widget build(BuildContext context)=>Container(padding:const EdgeInsets.symmetric(horizontal:14,vertical:7),decoration:BoxDecoration(color:color.withAlpha(25),border:Border.all(color:color),borderRadius:BorderRadius.circular(16)),child:Text('$name  $score',style:TextStyle(color:color,fontWeight:FontWeight.w900,fontSize:16)));}
class _HockeyPainter extends CustomPainter{const _HockeyPainter(this.puck,this.bottom,this.top);final Offset puck,bottom,top;Offset p(Offset x,Size s)=>Offset(x.dx*s.width,x.dy*s.height);@override void paint(Canvas c,Size s){final rect=Offset.zero&s;c.drawRRect(RRect.fromRectAndRadius(rect,const Radius.circular(30)),Paint()..shader=const LinearGradient(colors:[Color(0xFF071B33),Color(0xFF0B3556),Color(0xFF071B33)],begin:Alignment.topCenter,end:Alignment.bottomCenter).createShader(rect));final line=Paint()..color=const Color(0x8838BDF8)..style=PaintingStyle.stroke..strokeWidth=3;c.drawLine(Offset(0,s.height/2),Offset(s.width,s.height/2),line);c.drawCircle(Offset(s.width/2,s.height/2),s.width*.14,line);c.drawRRect(RRect.fromRectAndRadius(Rect.fromCenter(center:Offset(s.width/2,0),width:s.width*.38,height:22),const Radius.circular(12)),Paint()..color=const Color(0xFFF472B6));c.drawRRect(RRect.fromRectAndRadius(Rect.fromCenter(center:Offset(s.width/2,s.height),width:s.width*.38,height:22),const Radius.circular(12)),Paint()..color=const Color(0xFF22D3EE));_disc(c,p(top,s),s.width*.065,const Color(0xFFF472B6));_disc(c,p(bottom,s),s.width*.065,const Color(0xFF22D3EE));_disc(c,p(puck,s),s.width*.035,Colors.white);}
void _disc(Canvas c,Offset center,double r,Color color){c.drawCircle(center,r,Paint()..color=const Color(0x55000000)..maskFilter=const MaskFilter.blur(BlurStyle.normal,8));c.drawCircle(center,r,Paint()..shader=RadialGradient(colors:[Colors.white,color]).createShader(Rect.fromCircle(center:center,radius:r)));} @override bool shouldRepaint(covariant _HockeyPainter old)=>true;}