import 'dart:async';
import 'dart:math';
import 'package:flutter/material.dart';
import '../services/sound_service.dart';
import '../widgets/confetti_overlay.dart';
import '../widgets/game_header.dart';

class BattleshipPage extends StatefulWidget { const BattleshipPage({super.key}); @override State<BattleshipPage> createState()=>_BattleshipPageState(); }
class _BattleshipPageState extends State<BattleshipPage> {
  static const n=8; final random=Random(); final confettiKey=GlobalKey<ConfettiOverlayState>(); Timer? timer;
  bool bot=true,placing=true,covered=false; int player=0,placingPlayer=0; int? winner; late List<List<Set<int>>> fleets; late List<Set<int>> shots;
  @override void initState(){super.initState();_reset();}
  List<Set<int>> _fleet(){final ships=<Set<int>>[];for(final length in const [4,3,3,2]){while(true){final horizontal=random.nextBool();final r=random.nextInt(horizontal?n:n-length+1),c=random.nextInt(horizontal?n-length+1:n);final ship=<int>{for(var k=0;k<length;k++)(r+(horizontal?0:k))*n+c+(horizontal?k:0)};if(ships.every((s)=>s.intersection(ship).isEmpty)){ships.add(ship);break;}}}return ships;}
  void _reset(){timer?.cancel();fleets=[_fleet(),_fleet()];shots=[<int>{},<int>{}];setState((){player=0;placingPlayer=0;winner=null;placing=true;covered=false;});}
  void _mode(bool value){if(bot==value)return;bot=value;_reset();}
  bool _shipAt(int owner,int cell)=>fleets[owner].any((ship)=>ship.contains(cell));
  int _remaining(int owner)=>fleets[owner].where((ship)=>!ship.every(shots[1-owner].contains)).length;
  void _confirmFleet(){if(bot){setState((){placing=false;player=0;});}else if(placingPlayer==0){setState((){placingPlayer=1;covered=true;});}else{setState((){placing=false;player=0;covered=true;});}}
  void _fire(int cell,{bool robot=false}){if(placing||winner!=null||covered||(bot&&player==1&&!robot)||shots[player].contains(cell))return;final hit=_shipAt(1-player,cell);setState(()=>shots[player].add(cell));SoundService.instance.play(hit?'wrong.wav':'tap.wav');if(fleets[1-player].every((ship)=>ship.every(shots[player].contains))){setState(()=>winner=player);confettiKey.currentState?.burst(count:36);SoundService.instance.play('win.wav');return;}setState((){player=1-player;covered=!bot;});if(bot&&player==1)_bot();}
  void _bot(){timer?.cancel();timer=Timer(const Duration(milliseconds:750),(){if(!mounted||winner!=null||player!=1)return;final open=<int>[for(var i=0;i<64;i++)if(!shots[1].contains(i))i];final near=open.where((i)=>_neighbors(i).any((x)=>shots[1].contains(x)&&_shipAt(0,x))).toList();final pool=near.isNotEmpty?near:open;_fire(pool[random.nextInt(pool.length)],robot:true);});}
  Iterable<int> _neighbors(int i) sync*{final r=i~/n,c=i%n;if(r>0)yield i-n;if(r<n-1)yield i+n;if(c>0)yield i-1;if(c<n-1)yield i+1;}
  @override void dispose(){timer?.cancel();super.dispose();}
  @override Widget build(BuildContext context){final subtitle=placing?'رتّب أسطول اللاعب ${placingPlayer+1} ثم ابدأ':winner!=null?'فاز ${bot&&winner==1?'الروبوت':'اللاعب ${winner!+1}'} 🎉':covered?'سلّم الجهاز للاعب ${player+1}':bot&&player==1?'الروبوت يحدد الهدف...':'هاجم شبكة الخصم';return ConfettiOverlay(key:confettiKey,child:Padding(padding:const EdgeInsets.fromLTRB(14,8,14,14),child:Column(children:[
    GameHeader(title:'معركة السفن',subtitle:subtitle,color:const Color(0xFF0369A1),onReset:_reset),const SizedBox(height:7),
    Row(children:[Expanded(child:ChoiceChip(label:const Text('ضد الروبوت'),selected:bot,onSelected:(_)=>_mode(true))),const SizedBox(width:8),Expanded(child:ChoiceChip(label:const Text('مع صديق'),selected:!bot,onSelected:(_)=>_mode(false)))]),const SizedBox(height:8),
    if(placing)...[const Text('هذه شبكة أسطولك — الأزرق الداكن يمثل السفن',style:TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:8),Expanded(child:Stack(children:[_Grid(owner:placingPlayer,shots:const <int>{},fleets:fleets,revealShips:true,onTap:null),if(covered)Positioned.fill(child:Container(color:const Color(0xFF082F49),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text('سلّم الجهاز للاعب ${placingPlayer+1}',style:const TextStyle(color:Colors.white,fontSize:21,fontWeight:FontWeight.w900)),const SizedBox(height:12),FilledButton(onPressed:()=>setState(()=>covered=false),child:const Text('أنا جاهز'))]))) ])),const SizedBox(height:8),Row(children:[Expanded(child:OutlinedButton.icon(onPressed:covered?null:(){setState(()=>fleets[placingPlayer]=_fleet());},icon:const Icon(Icons.shuffle),label:const Text('توزيع جديد'))),const SizedBox(width:8),Expanded(child:FilledButton.icon(onPressed:covered?null:_confirmFleet,icon:const Icon(Icons.check),label:Text(bot||placingPlayer==1?'ابدأ المعركة':'تأكيد اللاعب 1')))])]
    else...[Row(children:[Expanded(child:_MiniFleet(owner:player,shots:shots[1-player],fleets:fleets)),const SizedBox(width:8),Column(children:[Text('سفنك: ${_remaining(player)}',style:const TextStyle(fontWeight:FontWeight.w900)),Text('سفن الخصم: ${_remaining(1-player)}',style:const TextStyle(fontWeight:FontWeight.w900,color:Color(0xFFF97316)))])]),const SizedBox(height:8),const Text('شبكة هجومك — اضغط مربعًا لإطلاق النار',style:TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:7),Expanded(child:Stack(children:[_Grid(owner:1-player,shots:shots[player],fleets:fleets,revealShips:false,onTap:_fire),if(covered)Positioned.fill(child:Container(color:const Color(0xFF082F49),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[const Icon(Icons.visibility_off,color:Colors.white,size:54),Text('سلّم الجهاز للاعب ${player+1}',style:const TextStyle(color:Colors.white,fontSize:21,fontWeight:FontWeight.w900)),const SizedBox(height:12),FilledButton(onPressed:()=>setState(()=>covered=false),child:const Text('أنا جاهز'))]))) ]))]
  ]))));}
}
class _Grid extends StatelessWidget{const _Grid({required this.owner,required this.shots,required this.fleets,required this.revealShips,required this.onTap});final int owner;final Set<int> shots;final List<List<Set<int>>> fleets;final bool revealShips;final ValueChanged<int>? onTap;bool ship(int i)=>fleets[owner].any((s)=>s.contains(i));@override Widget build(BuildContext context)=>AspectRatio(aspectRatio:1,child:GridView.builder(physics:const NeverScrollableScrollPhysics(),gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:8),itemCount:64,itemBuilder:(context,i){final fired=shots.contains(i),hit=fired&&ship(i),show=ship(i)&&revealShips;return GestureDetector(onTap:onTap==null?null:()=>onTap!(i),child:Container(margin:const EdgeInsets.all(1),decoration:BoxDecoration(color:show?const Color(0xFF0F3554):const Color(0xFF0284C7),borderRadius:BorderRadius.circular(4),border:Border.all(color:const Color(0x665DEBFF))),child:fired?Icon(hit?Icons.close_rounded:Icons.circle,color:hit?Colors.redAccent:Colors.white,size:hit?28:9):show?const Icon(Icons.directions_boat,color:Colors.white,size:18):null));}));}
class _MiniFleet extends StatelessWidget{const _MiniFleet({required this.owner,required this.shots,required this.fleets});final int owner;final Set<int> shots;final List<List<Set<int>>> fleets;@override Widget build(BuildContext context)=>SizedBox(width:112,height:112,child:_Grid(owner:owner,shots:shots,fleets:fleets,revealShips:true,onTap:null));}