import 'dart:math';
import 'package:flutter/material.dart';
import '../services/sound_service.dart';
import '../widgets/confetti_overlay.dart';
import '../widgets/game_header.dart';

class PenaltyShootoutPage extends StatefulWidget{const PenaltyShootoutPage({super.key});@override State<PenaltyShootoutPage> createState()=>_PenaltyShootoutPageState();}
class _PenaltyShootoutPageState extends State<PenaltyShootoutPage>{
 final random=Random();final confettiKey=GlobalKey<ConfettiOverlayState>();bool bot=true,humanShoots=true,waitingKeeper=false,finished=false,covered=false;int humanGoals=0,opponentGoals=0,humanKicks=0,opponentKicks=0;int? ballZone,keeperZone,pendingShot;
 void _reset(){setState((){humanShoots=true;waitingKeeper=false;finished=false;covered=false;humanGoals=opponentGoals=humanKicks=opponentKicks=0;ballZone=keeperZone=pendingShot=null;});}
 void _mode(bool value){bot=value;_reset();}
 void _choose(int zone){if(finished||waitingKeeper||covered)return;if(!bot){if(pendingShot==null){setState((){pendingShot=zone;covered=true;});return;}final shot=pendingShot!;pendingShot=null;_resolve(shot,zone,humanShoots);return;}if(humanShoots){_resolve(zone,random.nextInt(3),true);}else{_resolve(random.nextInt(3),zone,false);}}
  Future<void> _resolve(int shot,int keeper,bool firstShooter)async{final goal=shot!=keeper;setState((){ballZone=shot;keeperZone=keeper;waitingKeeper=true;if(firstShooter){humanKicks++;if(goal)humanGoals++;}else{opponentKicks++;if(goal)opponentGoals++;}});SoundService.instance.play(goal?'chime.wav':'wrong.wav');await Future<void>.delayed(const Duration(milliseconds:850));if(!mounted)return;setState((){waitingKeeper=false;ballZone=keeperZone=null;if(humanKicks>=5&&humanKicks==opponentKicks&&humanGoals!=opponentGoals){finished=true;confettiKey.currentState?.burst();SoundService.instance.play('win.wav');}else{humanShoots=!humanShoots;}});}
 String get message=>finished?'انتهت الركلات: $humanGoals - $opponentGoals':covered?'سلّم الجهاز إلى حارس المرمى':waitingKeeper?(ballZone==keeperZone?'تصدي رائع! 🧤':'هدف! ⚽'):!bot&&pendingShot!=null?'اختر جهة قفز الحارس':humanShoots?'اختر مكان تسديد الكرة':'أنت الحارس — اختر جهة القفز';
 @override Widget build(BuildContext context)=>ConfettiOverlay(key:confettiKey,child:Padding(padding:const EdgeInsets.fromLTRB(14,8,14,14),child:Column(children:[
  GameHeader(title:'ركلات الترجيح',subtitle:message,color:const Color(0xFF15803D),onReset:_reset),const SizedBox(height:7),
  Row(children:[Expanded(child:ChoiceChip(label:const Text('ضد الروبوت'),selected:bot,onSelected:(_)=>_mode(true))),const SizedBox(width:8),Expanded(child:ChoiceChip(label:const Text('مع صديق'),selected:!bot,onSelected:(_)=>_mode(false)))]),const SizedBox(height:9),
  Row(mainAxisAlignment:MainAxisAlignment.spaceEvenly,children:[_Team(name:'أنت',score:humanGoals,kicks:humanKicks,color:const Color(0xFF22C55E)),Text('$humanGoals  :  $opponentGoals',style:const TextStyle(fontSize:28,fontWeight:FontWeight.w900)),_Team(name:bot?'الروبوت':'اللاعب 2',score:opponentGoals,kicks:opponentKicks,color:const Color(0xFFEF4444))]),const SizedBox(height:10),
  Expanded(child:Stack(children:[Positioned.fill(child:CustomPaint(painter:_GoalPainter(ballZone,keeperZone,humanShoots),child:const SizedBox.expand())),if(covered)Positioned.fill(child:Container(color:const Color(0xDD14532D),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[const Icon(Icons.sports_handball,color:Colors.white,size:52),const Text('سلّم الجهاز إلى حارس المرمى',style:TextStyle(color:Colors.white,fontSize:19,fontWeight:FontWeight.w900)),const SizedBox(height:12),FilledButton(onPressed:()=>setState(()=>covered=false),child:const Text('الحارس جاهز'))]))) ])),const SizedBox(height:10),
  Row(children:[for(var i=0;i<3;i++)Expanded(child:Padding(padding:EdgeInsetsDirectional.only(start:i==0?0:7),child:FilledButton(onPressed:waitingKeeper||finished?null:()=>_choose(i),style:FilledButton.styleFrom(backgroundColor:const Color(0xFF15803D),padding:const EdgeInsets.symmetric(vertical:14)),child:Text(const ['يسار','الوسط','يمين'][i],style:const TextStyle(fontWeight:FontWeight.w900)))))]),
 ])));
}
class _Team extends StatelessWidget{const _Team({required this.name,required this.score,required this.kicks,required this.color});final String name;final int score,kicks;final Color color;@override Widget build(BuildContext context)=>Column(children:[Text(name,style:TextStyle(color:color,fontWeight:FontWeight.w900)),Text('$score هدف • $kicks/5',style:const TextStyle(fontSize:12))]);}
class _GoalPainter extends CustomPainter{const _GoalPainter(this.ball,this.keeper,this.shooting);final int? ball,keeper;final bool shooting;@override void paint(Canvas c,Size s){final sky=Rect.fromLTWH(0,0,s.width,s.height*.58);c.drawRect(sky,Paint()..shader=const LinearGradient(colors:[Color(0xFF7DD3FC),Color(0xFFE0F2FE)],begin:Alignment.topCenter,end:Alignment.bottomCenter).createShader(sky));c.drawRect(Rect.fromLTWH(0,s.height*.58,s.width,s.height*.42),Paint()..color=const Color(0xFF22A447));final goal=Rect.fromLTWH(s.width*.12,s.height*.18,s.width*.76,s.height*.48);final line=Paint()..color=Colors.white..style=PaintingStyle.stroke..strokeWidth=7;c.drawRect(goal,line);for(var i=1;i<6;i++)c.drawLine(Offset(goal.left+goal.width*i/6,goal.top),Offset(goal.left+goal.width*i/6,goal.bottom),Paint()..color=const Color(0x88FFFFFF));final zone=keeper??1;final k=Offset(goal.left+goal.width*(zone+.5)/3,goal.bottom-s.height*.08);c.drawCircle(k,s.width*.045,Paint()..color=const Color(0xFFF59E0B));c.drawLine(k+Offset(0,s.width*.04),k+Offset(0,s.width*.13),Paint()..color=const Color(0xFF1D4ED8)..strokeWidth=12..strokeCap=StrokeCap.round);final b=ball==null?Offset(s.width*.5,s.height*.88):Offset(goal.left+goal.width*(ball!+.5)/3,goal.top+goal.height*.55);c.drawCircle(b,s.width*.038,Paint()..color=Colors.white);c.drawCircle(b,s.width*.038,Paint()..color=Colors.black..style=PaintingStyle.stroke..strokeWidth=3);}
 @override bool shouldRepaint(covariant _GoalPainter old)=>true;}